CREATE TABLE users (
    ID INTEGER PRIMARY KEY NOT NULL,
    USERNAME TEXT NOT NULL,
    IS_ADMIN BOOLEAN,
    FIRST_NAME VARCHAR (10),
    LAST_NAME VARCHAR (10),
    PASSWORD VARCHAR(400)
                   );