CREATE TABLE users (
    ID SERIAL,
    USERNAME TEXT NOT NULL,
    IS_ADMIN BOOLEAN,
    FIRST_NAME VARCHAR (10),
    LAST_NAME VARCHAR (10),
    PASSWORD VARCHAR(400)
                   );

INSERT INTO users (USERNAME, IS_ADMIN, PASSWORD)
VALUES ('admin', TRUE, '$2b$12$5fELMc9C42vz2l2IOLJ0ve1GJ02FVwg7ujapgKMZ/m/qBnrK14pOe');

CREATE TABLE products (
    ID SERIAL,
    CATEGORY TEXT NOT NULL,
    PRODUCT_NAME TEXT NOT NULL ,
    DESCRIPTION VARCHAR(300),
    PRICE INT NOT NULL,
    IN_STOCK INT NOT NULL,
    IMG_PATH VARCHAR(200)
);